# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=1)),
                ('race_ethnic', models.TextField(max_length=25)),
                ('compid', models.IntegerField(default=1)),
                ('recno', models.IntegerField(default=1)),
                ('race', models.CharField(max_length=1)),
                ('ethnicity', models.CharField(default=b'W', max_length=1)),
                ('age_years', models.IntegerField(default=1)),
                ('pwgtp', models.IntegerField(default=1)),
                ('pool', models.IntegerField(default=1)),
                ('income', models.IntegerField()),
                ('ages', models.CharField(max_length=30)),
                ('genders', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=1)),
                ('age_months', models.IntegerField(default=1)),
                ('mean_logh', models.DecimalField(decimal_places=10, max_digits=11)),
                ('mean_logbw', models.DecimalField(decimal_places=10, max_digits=11)),
                ('logbw_resid', models.DecimalField(decimal_places=10, max_digits=11)),
                ('logh_resid', models.DecimalField(decimal_places=10, max_digits=11)),
                ('weight', models.DecimalField(decimal_places=6, max_digits=9)),
                ('weight_adj', models.DecimalField(decimal_places=10, max_digits=13)),
                ('height', models.DecimalField(decimal_places=8, max_digits=11)),
                ('baths', models.IntegerField(default=1)),
                ('bedrms', models.IntegerField(default=1)),
                ('cars', models.IntegerField(default=1)),
                ('cellar', models.IntegerField(default=1)),
                ('hequip', models.IntegerField(default=1)),
                ('lot', models.IntegerField(default=1)),
                ('pwt', models.DecimalField(decimal_places=8, max_digits=13)),
                ('rooms', models.IntegerField(default=1)),
                ('sewdis', models.IntegerField(default=1)),
                ('unitsf', models.IntegerField(default=1)),
                ('water', models.IntegerField(default=1)),
                ('waterd', models.IntegerField(default=1)),
                ('kownrent', models.IntegerField(default=1)),
                ('condcoop', models.IntegerField(default=1)),
                ('stories', models.IntegerField(default=1)),
                ('stoven', models.IntegerField(default=1)),
                ('oven', models.IntegerField(default=1)),
                ('ovenuse', models.IntegerField(default=1)),
                ('outgrill', models.IntegerField(default=1)),
                ('dishwash', models.IntegerField(default=1)),
                ('cwasher', models.IntegerField(default=1)),
                ('washload', models.IntegerField(default=1)),
                ('dryer', models.IntegerField(default=1)),
                ('dryruse', models.IntegerField(default=1)),
                ('tvcolor', models.IntegerField(default=1)),
                ('computer', models.IntegerField(default=1)),
                ('numpc', models.IntegerField(default=1)),
                ('pcprint', models.IntegerField(default=1)),
                ('swim', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
