# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    # auto generated RunParams
    dependencies = [
        ('hem_app', '0004_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(default=b'NMO', max_length=20)),
                ('gender', models.CharField(default=b'B', max_length=1)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('max_age', models.PositiveSmallIntegerField(default=100)),
                ('pop_gen_seed', models.PositiveIntegerField(default=1)),
                ('population_size', models.PositiveIntegerField(default=10000)),
                ('race', models.CharField(default=b'WBNAPO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('population_size',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_type', 'product_type_refined')},
        ),
        migrations.AlterModelOptions(
            name='runhistory',
            options={'ordering': ('created_at',)},
        ),
    ]
