# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ auto generated Product Assignment """
    dependencies = [
        ('hem_app', '0005_auto_20170306_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.TextField(max_length=2)),
                ('title', models.TextField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.TextField(default=b'other', max_length=75),
        ),
        migrations.AddField(
            model_name='product',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hem_app.ProductAssignment'),
        ),
    ]
