# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0005_auto_20170330_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemical',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
