# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0006_auto_20170331_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age_months',
            new_name='row',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bedrms',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cellar',
        ),
        migrations.RemoveField(
            model_name='person',
            name='compid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='condcoop',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hequip',
        ),
        migrations.RemoveField(
            model_name='person',
            name='income',
        ),
        migrations.RemoveField(
            model_name='person',
            name='logbw_resid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='logh_resid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mean_logbw',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mean_logh',
        ),
        migrations.RemoveField(
            model_name='person',
            name='numpc',
        ),
        migrations.RemoveField(
            model_name='person',
            name='oven',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ovenuse',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pwgtp',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pwt',
        ),
        migrations.RemoveField(
            model_name='person',
            name='race_ethnic',
        ),
        migrations.RemoveField(
            model_name='person',
            name='recno',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stories',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tvcolor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='water',
        ),
        migrations.RemoveField(
            model_name='person',
            name='waterd',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight_adj',
        ),
        migrations.AddField(
            model_name='person',
            name='bsa_adj',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='person',
            name='high_ceil',
            field=models.IntegerField(default=0),
        ),
    ]
