# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """ auto generated product """
    dependencies = [
        ('hem_app', '0006_auto_20170307_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sheds_id',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sheds_product_category_id',
            field=models.TextField(default=b'', max_length=50),
        ),
    ]
