# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0007_auto_20170308_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type_refined',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='puc_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheds_id',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheds_product_category_id',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
