# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0007_auto_20170413_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behave_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'', max_length=120)),
                ('day_of_year', models.IntegerField(default=1)),
                ('dataset_id', models.IntegerField(default=1)),
                ('puc_id', models.TextField(default=b'', max_length=120)),
                ('start_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('person', 'dataset_id'),
                'verbose_name_plural': 'behave_activities',
            },
        ),
        migrations.CreateModel(
            name='Behave_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(default=1)),
                ('duration', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('formulation_id', models.IntegerField(default=1)),
                ('frequency', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('mass', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('puc_id', models.TextField(default=b'', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('person', 'dataset_id'),
                'verbose_name_plural': 'behave_people',
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='run_id',
            new_name='dataset_id',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='run_id',
        ),
        migrations.AddField(
            model_name='dose',
            name='dataset_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='behave_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Person'),
        ),
        migrations.AddField(
            model_name='behave_activity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Person'),
        ),
    ]
