# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0008_auto_20170414_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ages',
            field=models.CharField(max_length=50),
        ),
    ]
