# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0010_runhistory_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Category'),
        ),
    ]
