# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0012_auto_20170424_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='half_air_hr',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
