# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ auto generated run history """

    dependencies = [
        ('hem_app', '0012_auto_20170328_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hem_app.ProductAssignment'),
        ),
    ]
