# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0013_auto_20170426_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation_id', models.IntegerField()),
                ('weight_fraction', models.DecimalField(decimal_places=12, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Chemical')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='neverever',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='behave_activity',
            name='puc_id',
        ),
        migrations.RemoveField(
            model_name='behave_person',
            name='puc_id',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='puc_id',
        ),
        migrations.RemoveField(
            model_name='neverever',
            name='puc_id',
        ),
        migrations.AddField(
            model_name='behave_activity',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behave_person',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neverever',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='puc_id',
            field=models.TextField(default=b'', max_length=120),
        ),
        migrations.AddField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
        ),
    ]
