# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0014_auto_20170328_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductAssignment',
            new_name='Assignment',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type_refined',
        ),
        migrations.RemoveField(
            model_name='product',
            name='puc_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sheds_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sheds_product_category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trait',
            name='products',
            field=models.ManyToManyField(through='hem_app.ProductTrait', to='hem_app.Product'),
        ),
        migrations.AddField(
            model_name='producttrait',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
        ),
        migrations.AddField(
            model_name='producttrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Trait'),
        ),
        migrations.AddField(
            model_name='product',
            name='traits',
            field=models.ManyToManyField(through='hem_app.ProductTrait', to='hem_app.Trait'),
        ),
    ]
