# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0014_auto_20170426_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='data_type',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composition',
            name='productcomp_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
