# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0015_auto_20170426_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='neverever',
            name='age19_49',
            field=models.BooleanField(default=False),
        ),
    ]
