# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0015_auto_20170329_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='assignment',
        ),
    ]
