# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0016_neverever_age19_49'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(default=1)),
                ('person_household_index', models.IntegerField()),
                ('person_diary', models.IntegerField()),
                ('diary_category', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=1)),
                ('age', models.IntegerField()),
                ('day_of_year', models.IntegerField(default=1)),
                ('start_time_hr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_hr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity_code', models.IntegerField()),
                ('dur_ht', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dur_iet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dur_oet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dur_det', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flag', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product')),
            ],
            options={
                'ordering': ('person', 'dataset_id'),
                'verbose_name_plural': 'behave_people',
            },
        ),
        migrations.RemoveField(
            model_name='behave_activity',
            name='person',
        ),
        migrations.RemoveField(
            model_name='behave_activity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='behave_person',
            name='person',
        ),
        migrations.RemoveField(
            model_name='behave_person',
            name='product',
        ),
        migrations.DeleteModel(
            name='Behave_Activity',
        ),
        migrations.DeleteModel(
            name='Behave_Person',
        ),
    ]
