# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0018_auto_20170501_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='disposal_outdoor_surface_ug',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dose',
            name='disposal_sanitary_drain_ug',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dose',
            name='disposal_solid_waste_ug',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dose',
            name='disposal_window_ug',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dose',
            name='intake_derm_mgkgBW_d',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dose',
            name='intake_inhal_mgkgBW_d',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dose',
            name='peak_dermal_loading_ug',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dose',
            name='peak_hourly_air_conc_ug_m3',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
