# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0020_auto_20170503_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='fabs',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
