# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0021_chemical_fabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dose',
            name='dataset_id',
        ),
        migrations.AddField(
            model_name='dose',
            name='runparams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hem_app.RunParams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runparams',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
        ),
    ]
