# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0022_auto_20170504_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runhistory',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Category'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Chemical'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='gender',
            field=models.CharField(choices=[(b'B', b'Both'), (b'F', b'Female'), (b'M', b'Male')], default=b'B', max_length=1),
        ),
    ]
