# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0024_auto_20170530_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCycleImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_frac_chem_puc', models.FloatField()),
                ('mass_puc_use_adult', models.FloatField()),
                ('pif_derm_adult', models.FloatField()),
                ('pif_inhal_adult', models.FloatField()),
                ('pif_ingest_adult', models.FloatField()),
                ('mass_puc_use_child', models.FloatField()),
                ('pif_derm_child', models.FloatField()),
                ('pif_inhal_child', models.FloatField()),
                ('pif_ingest_child', models.FloatField()),
                ('chem_mass', models.FloatField()),
                ('mass_tot_air', models.FloatField()),
                ('mass_tot_water', models.FloatField()),
                ('mass_tot_land', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Chemical')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product')),
                ('runparams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hem_app.RunParams')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
