# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0025_lifecycleimpact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'ordering': ('cas', 'title')},
        ),
        migrations.AddField(
            model_name='runparams',
            name='notes',
            field=models.TextField(default=None),
        ),
    ]
