# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0026_auto_20170601_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runhistory',
            old_name='products',
            new_name='is_product',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='categories',
        ),
        migrations.AddField(
            model_name='runhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hem_app.Product'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=99),
        ),
    ]
