# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0027_auto_20170607_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sheds_id',
            field=models.TextField(default=b'', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='puc_id',
            field=models.TextField(default=b'', max_length=17),
        ),
    ]
