# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0028_auto_20170616_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_years',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(db_index=True, max_length=1),
        ),
    ]
