# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hem_app', '0030_auto_20170630_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='behavior',
            options={'verbose_name_plural': 'behave_people'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chemical',
            options={},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dose',
            options={},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lifecycleimpact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='neverever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='runhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='runparams',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={},
        ),
        migrations.AddField(
            model_name='runparams',
            name='chem_seed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='runparams',
            name='comp_method',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='runparams',
            name='house_seed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='runparams',
            name='puc_offset',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='runparams',
            name='puc_seed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='runparams',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='runparams',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
